---
version: "3.8"
services:

  opencve: &opencve_base
    image: opencve/opencve:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TINI_VERSION: ${TINI_VERSION}
    environment:
      DATABASE_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
    - opencve-data:/opt/opencve/data
    - opencve-logs:/opt/opencve/logs
    networks:
    - internal
    - web

  server:
    <<: *opencve_base
    container_name: ${NAMESPACE}-server
    ports:
    - 8000:8000
    # expose:
    # - 8000
    depends_on:
    - celery-worker
    - celery-beat
    - postgres
    networks:
    - internal
    - web
    restart: unless-stopped

  celery-worker:
    <<: *opencve_base
    container_name: ${NAMESPACE}-worker
    networks:
    - internal
    command: ["worker"]
    restart: unless-stopped

  celery-beat:
    <<: *opencve_base
    container_name: ${NAMESPACE}-beat
    networks:
    - internal
    command: ["beat"]
    restart: unless-stopped  

  postgres:
    image: postgres:${POSTGRES_VERSION}-alpine
    container_name: ${NAMESPACE}-postgres
    ports:
    - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
    - ${POSTGRES_PORT}
    networks:
    - internal
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    volumes:
    - postgres-data:/var/lib/postgresql/data/
    restart: unless-stopped

networks:
  internal:
    driver: bridge
  web:
    external: true

volumes:
  # server data
  opencve-data:
  opencve-logs:
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/shared/logs/opencve
  # PostreSQL
  postgres-data: