# Generated by Django 5.2.11 on 2026-05-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cves", "0003_variable"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name", "id"], name="ix_products_name_id"),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["name", "id"], name="ix_vendors_name_id"),
        ),
    ]
