# Generated by Django 5.2.11 on 2026-06-08 12:47

from django.db import migrations


WEAKNESS_SQL = """
CREATE PROCEDURE weakness_upsert(
    cwe         text,
    created     timestamptz,
    updated     timestamptz,
    name        text,
    description text
)
LANGUAGE plpgsql
AS $$
BEGIN
    -- add a new CWE or update an existing one
    INSERT INTO opencve_weaknesses (id, created_at, updated_at, cwe_id, name, description)
    VALUES(uuid_generate_v4(), created, updated, cwe, name, description)
    ON CONFLICT (cwe_id) DO
    UPDATE SET
      updated_at = EXCLUDED.updated_at,
      name = EXCLUDED.name,
      description = EXCLUDED.description;
END;
$$;
"""
WEAKNESS_REVERSE_SQL = """
DROP PROCEDURE weakness_upsert(
    cwe         text,
    created     timestamptz,
    updated     timestamptz,
    name        text,
    description text
);"""


class Migration(migrations.Migration):

    dependencies = [
        ("cves", "0004_add_vendor_product_keyset_indexes"),
    ]

    operations = [
        migrations.RunSQL(sql=WEAKNESS_SQL, reverse_sql=WEAKNESS_REVERSE_SQL),
    ]
