# Generated by Django 4.2.3 on 2024-01-09 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cves', '0004_remove_cve_ix_cves_cwes_remove_cve_ix_cves_summary_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cwe',
            new_name='Weakness',
        ),
        migrations.AlterModelTable(
            name='weakness',
            table='opencve_weaknesses',
        ),
    ]
