# Generated by Django 4.2.3 on 2024-01-12 09:59

import django.contrib.postgres.indexes
from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("cves", "0005_rename_cwe_weakness_alter_weakness_table"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cve",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("title"), name="gin_trgm_ops"
                ),
                name="ix_cves_title",
            ),
        ),
    ]
