# Generated by Django 4.2.3 on 2024-01-12 10:18

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cves", "0006_cve_ix_cves_title"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cve",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metrics"], name="ix_cves_metrics"
            ),
        ),
    ]
