# Generated by Django 4.2.3 on 2023-11-06 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="user",
            new_name="owner",
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("invited", "invited"),
                            ("owner", "owner"),
                            ("member", "member"),
                        ],
                        default="member",
                        max_length=10,
                    ),
                ),
                ("date_invited", models.DateField(default=django.utils.timezone.now)),
                ("date_joined", models.DateField(blank=True, null=True)),
                ("key", models.CharField(max_length=64, unique=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="organization",
            name="members",
            field=models.ManyToManyField(
                through="organizations.Membership", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
