# Generated by Django 5.2.11 on 2026-04-14 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_normalize_membership_email_and_link_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership_set",
                to="organizations.organization",
            ),
        ),
    ]
