# Generated by Django 4.2.3 on 2023-11-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0008_remove_membership_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[("owner", "owner"), ("member", "member")],
                default="member",
                max_length=20,
            ),
        ),
    ]
