# Generated by Django 5.2.1 on 2025-11-05 06:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cves", "0003_variable"),
        ("projects", "0004_alter_project_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CveTracker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("to_evaluate", "To evaluate"),
                            ("pending_review", "Pending review"),
                            ("analysis_in_progress", "Analysis in progress"),
                            ("remediation_in_progress", "Remediation in progress"),
                            ("evaluated", "Evaluated"),
                            ("resolved", "Resolved"),
                            ("not_applicable", "Not applicable"),
                            ("risk_accepted", "Risk accepted"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_cves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trackers",
                        to="cves.cve",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cve_trackers",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "opencve_cve_trackers",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cve", "project"), name="ix_unique_cve_project_tracker"
                    )
                ],
            },
        ),
    ]
