# Generated by Django 5.1.4 on 2025-01-23 21:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_project_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the saved view",
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Special characters (except dash) are not accepted",
                                regex="^[a-zA-Z0-9\\-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "query",
                    models.TextField(
                        help_text="The advanced search query (e.g., 'vendor:microsoft AND cvss31>=8')"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("project", "name")},
            },
        ),
    ]
