# Generated by Django 5.1.4 on 2025-02-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_projectview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectview",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="projectview",
            name="query",
            field=models.TextField(),
        ),
    ]
