# Generated by Django (data migration)

import secrets

from django.db import migrations


def add_unsubscribe_tokens(apps, schema_editor):
    """Add unsubscribe tokens to the existingemail notifications."""
    Notification = apps.get_model("projects", "Notification")
    for notification in Notification.objects.filter(type="email"):
        config = notification.configuration or {}
        extras = dict(config.get("extras") or {})
        if "unsubscribe_token" not in extras:
            extras["unsubscribe_token"] = secrets.token_urlsafe(32)
            config["extras"] = extras
            notification.configuration = config
            notification.save(update_fields=["configuration"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_cvetracker"),
    ]

    operations = [
        migrations.RunPython(add_unsubscribe_tokens, noop),
    ]
