# Generated by Django 5.2.1 on 2026-02-16 10:00:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import projects.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_add_email_notification_unsubscribe_tokens"),
    ]

    operations = [
        migrations.CreateModel(
            name="Automation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Special characters (except dash and underscore) are not accepted",
                                regex="^[a-zA-Z0-9\\-_ ]+$",
                            )
                        ],
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "configuration",
                    models.JSONField(
                        default=projects.models.get_default_automation_config
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "opencve_automations",
            },
        ),
    ]
