# Generated by Django

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("changes", "0001_initial"),
        ("projects", "0007_automation"),
    ]

    operations = [
        migrations.AddField(
            model_name="automation",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("realtime", "Real-time monitoring"),
                    ("scheduled", "Scheduled report"),
                ],
                default="realtime",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="automation",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AutomationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("run_date", models.DateField(db_index=True)),
                ("matched_cves_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("failed", "Failed")],
                        default="sent",
                        max_length=20,
                    ),
                ),
                (
                    "automation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="projects.automation",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_runs",
                        to="changes.report",
                    ),
                ),
            ],
            options={
                "db_table": "opencve_automation_runs",
                "ordering": ["-run_date"],
            },
        ),
    ]
