# Generated by Django 5.2.11 on 2026-03-19 16:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import projects.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("changes", "0004_report_ai_summary"),
        ("projects", "0007_cvecomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Automation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Special characters (except dash and underscore) are not accepted",
                                regex="^[a-zA-Z0-9\\-_ ]+$",
                            )
                        ],
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("realtime", "Real-time monitoring"),
                            ("scheduled", "Scheduled report"),
                        ],
                        default="realtime",
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[("daily", "Daily"), ("weekly", "Weekly")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "schedule_timezone",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("schedule_time", models.TimeField(blank=True, null=True)),
                (
                    "schedule_weekday",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        default=projects.models.get_default_automation_config
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "opencve_automations",
            },
        ),
        migrations.CreateModel(
            name="AutomationExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("executed_at", models.DateTimeField(db_index=True)),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("matched_cves_count", models.IntegerField(default=0)),
                (
                    "impact_summary",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                (
                    "cves_table_data",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                (
                    "automation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="projects.automation",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_executions",
                        to="changes.report",
                    ),
                ),
            ],
            options={
                "db_table": "opencve_automation_executions",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="AutomationRunResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("output_type", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=256)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "automation_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="projects.automationexecution",
                    ),
                ),
            ],
            options={
                "db_table": "opencve_automation_execution_results",
                "ordering": ["created_at"],
            },
        ),
    ]
