# Generated by Django 5.2.11 on 2026-02-16 18:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_automation_trigger_frequency_automationrun"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationrun",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
