# Generated by Django

import django.db.models.deletion
import django.utils.timezone
import uuid
from datetime import datetime, time
from django.db import migrations, models


def fill_run_at_from_run_date(apps, schema_editor):
    """Populate run_at, window_start, window_end from run_date for existing runs."""
    AutomationRun = apps.get_model("projects", "AutomationRun")
    for run in AutomationRun.objects.all():
        run_date = run.run_date
        run.run_at = django.utils.timezone.make_aware(
            datetime.combine(run_date, time(0, 0))
        )
        run.window_start = run.run_at
        run.window_end = django.utils.timezone.make_aware(
            datetime.combine(run_date, time(23, 59, 59))
        )
        run.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("changes", "0001_initial"),
        ("projects", "0009_alter_automationrun_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationrun",
            name="run_at",
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="automationrun",
            name="window_start",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="automationrun",
            name="window_end",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(fill_run_at_from_run_date, noop),
        migrations.RemoveField(
            model_name="automationrun",
            name="run_date",
        ),
        migrations.AlterField(
            model_name="automationrun",
            name="run_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="automationrun",
            name="window_start",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="automationrun",
            name="window_end",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="automationrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Success"),
                    ("failed", "Failed"),
                    ("no_match", "No match"),
                    ("partial", "Partial"),
                ],
                default="sent",
                max_length=20,
            ),
        ),
        migrations.AlterModelOptions(
            name="automationrun",
            options={"db_table": "opencve_automation_runs", "ordering": ["-run_at"]},
        ),
        migrations.CreateModel(
            name="AutomationRunOutput",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("output_type", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=256)),
                (
                    "automation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outputs",
                        to="projects.automationrun",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_run_outputs",
                        to="changes.report",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="automation_run_outputs/",
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=512, null=True)),
            ],
            options={
                "db_table": "opencve_automation_run_outputs",
                "ordering": ["created_at"],
            },
        ),
    ]
