# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_automation_run_activity_and_outputs"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationrun",
            name="impact_summary",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="automationrun",
            name="cves_table_data",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="automationrunoutput",
            name="details",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
