# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_automation_run_impact_cves_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="automationrunoutput",
            name="report",
        ),
        migrations.RemoveField(
            model_name="automationrunoutput",
            name="file",
        ),
        migrations.RemoveField(
            model_name="automationrunoutput",
            name="url",
        ),
    ]
