# Generated by Django 5.2.11 on 2026-02-24 11:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("changes", "0004_report_ai_summary"),
        ("projects", "0016_rename_run_to_execution"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="automationexecution",
            options={"ordering": ["-executed_at"]},
        ),
        migrations.AlterField(
            model_name="automationexecution",
            name="automation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="projects.automation",
            ),
        ),
        migrations.AlterField(
            model_name="automationexecution",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="automation_executions",
                to="changes.report",
            ),
        ),
        migrations.AlterField(
            model_name="automationrunresult",
            name="automation_execution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="projects.automationexecution",
            ),
        ),
        migrations.AlterField(
            model_name="automationrunresult",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
