# Generated by Django 4.2.3 on 2023-08-02 19:42

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import projects.models
import projects.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=256, validators=[django.core.validators.RegexValidator(message='Special characters (except dash and underscore) are not accepted', regex='^[a-zA-Z0-9\\-_ ]+$')])),
                ('type', models.CharField(max_length=64)),
                ('is_enabled', models.BooleanField(default=True)),
                ('configuration', models.JSONField(default=projects.utils.get_default_configuration)),
            ],
            options={
                'db_table': 'opencve_notifications',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('subscriptions', models.JSONField(default=projects.models.get_default_subscriptions)),
            ],
            options={
                'db_table': 'opencve_projects',
            },
        ),
    ]
