# Generated by Django 4.2.3 on 2023-11-06 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_rename_user_organization_owner_membership_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={"permissions": (("add_member", "Add member"),)},
        ),
    ]
