# Generated by Django 4.2.3 on 2023-11-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_alter_membership_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[("owner", "owner"), ("member", "member")],
                default="member",
                max_length=10,
            ),
        ),
    ]
