# Generated by Django 4.2.3 on 2023-11-11 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0009_alter_membership_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="date_invited",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="date_joined",
            field=models.DateTimeField(
                blank=True, db_index=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
