# Generated by Django 5.2.1 on 2025-08-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("changes", "0003_add_report_upsert_procedure"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="ai_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
