from django.urls import path, register_converter

from opencve.utils import DateConverter
from projects.views import (
    AssignCveUserView,
    AutomationConfigurationView,
    AutomationCreateView,
    AutomationDeleteView,
    AutomationExecutionDrawerView,
    AutomationOverviewView,
    AutomationResultDetailView,
    AutomationResultsView,
    AutomationRunResultDownloadView,
    AutomationsView,
    CreateCveCommentView,
    DeleteCveCommentView,
    NotificationCreateView,
    NotificationsView,
    NotificationDeleteView,
    NotificationResendConfirmationView,
    NotificationUpdateView,
    ProjectCreateView,
    ProjectDeleteView,
    ProjectDetailView,
    ProjectEditView,
    ProjectsListView,
    ProjectVulnerabilitiesCsvExportView,
    ProjectVulnerabilitiesView,
    ReportsView,
    ReportView,
    SubscriptionsView,
    UpdateCveCommentView,
    UpdateCveStatusView,
)

register_converter(DateConverter, "date")

urlpatterns = [
    path("org/<org_name>/projects/", ProjectsListView.as_view(), name="list_projects"),
    path(
        "org/<org_name>/projects/add",
        ProjectCreateView.as_view(),
        name="create_project",
    ),
    path(
        "org/<org_name>/projects/<project_name>",
        ProjectDetailView.as_view(),
        name="project",
    ),
    path(
        "org/<org_name>/projects/<project_name>/edit",
        ProjectEditView.as_view(),
        name="edit_project",
    ),
    path(
        "org/<org_name>/projects/<project_name>/delete",
        ProjectDeleteView.as_view(),
        name="delete_project",
    ),
    path(
        "org/<org_name>/projects/<project_name>/notifications",
        NotificationsView.as_view(),
        name="notifications",
    ),
    path(
        "org/<org_name>/projects/<project_name>/notifications/add",
        NotificationCreateView.as_view(),
        name="create_notification",
    ),
    path(
        "org/<org_name>/projects/<project_name>/notifications/<notification>",
        NotificationUpdateView.as_view(),
        name="edit_notification",
    ),
    path(
        "org/<org_name>/projects/<project_name>/notifications/<notification>/resend-confirmation",
        NotificationResendConfirmationView.as_view(),
        name="resend_notification_confirmation",
    ),
    path(
        "org/<org_name>/projects/<project_name>/notifications/<notification>/delete",
        NotificationDeleteView.as_view(),
        name="delete_notification",
    ),
    path(
        "org/<org_name>/projects/<project_name>/reports",
        ReportsView.as_view(),
        name="reports",
    ),
    path(
        "org/<org_name>/projects/<project_name>/reports/<date:day>",
        ReportView.as_view(),
        name="report",
    ),
    path(
        "org/<org_name>/projects/<project_name>/subscriptions",
        SubscriptionsView.as_view(),
        name="subscriptions",
    ),
    path(
        "org/<org_name>/projects/<project_name>/automations",
        AutomationsView.as_view(),
        name="automations",
    ),
    path(
        "org/<org_name>/projects/<project_name>/automations/add/<str:trigger_type>/",
        AutomationCreateView.as_view(),
        name="create_automation",
    ),
    path(
        "org/<org_name>/projects/<project_name>/automations/<automation>",
        AutomationOverviewView.as_view(),
        name="automation_overview",
    ),
    path(
        "org/<org_name>/projects/<project_name>/automations/<automation>/configuration",
        AutomationConfigurationView.as_view(),
        name="automation_configuration",
    ),
    path(
        "org/<org_name>/projects/<project_name>/automations/<automation>/results",
        AutomationResultsView.as_view(),
        name="automation_results",
    ),
    path(
        "org/<org_name>/projects/<project_name>/automations/<automation>/results/<uuid:result_id>",
        AutomationResultDetailView.as_view(),
        name="automation_result_detail",
    ),
    path(
        "org/<org_name>/projects/<project_name>/automations/<automation>/executions/<uuid:execution_id>/drawer",
        AutomationExecutionDrawerView.as_view(),
        name="automation_execution_drawer",
    ),
    path(
        "org/<org_name>/projects/<project_name>/automations/<automation>/executions/<uuid:execution_id>/results/<uuid:result_id>/download",
        AutomationRunResultDownloadView.as_view(),
        name="automation_execution_result_download",
    ),
    path(
        "org/<org_name>/projects/<project_name>/automations/<automation>/delete",
        AutomationDeleteView.as_view(),
        name="delete_automation",
    ),
    path(
        "org/<org_name>/projects/<project_name>/vulnerabilities",
        ProjectVulnerabilitiesView.as_view(),
        name="project_vulnerabilities",
    ),
    path(
        "org/<org_name>/projects/<project_name>/vulnerabilities/export/csv",
        ProjectVulnerabilitiesCsvExportView.as_view(),
        name="project_vulnerabilities_export_csv",
    ),
    path(
        "org/<org_name>/projects/<project_name>/assign-cve-user",
        AssignCveUserView.as_view(),
        name="assign_cve_user",
    ),
    path(
        "org/<org_name>/projects/<project_name>/update-cve-status",
        UpdateCveStatusView.as_view(),
        name="update_cve_status",
    ),
    path(
        "org/<org_name>/projects/<project_name>/create-cve-comment",
        CreateCveCommentView.as_view(),
        name="create_cve_comment",
    ),
    path(
        "org/<org_name>/projects/<project_name>/update-cve-comment",
        UpdateCveCommentView.as_view(),
        name="update_cve_comment",
    ),
    path(
        "org/<org_name>/projects/<project_name>/delete-cve-comment",
        DeleteCveCommentView.as_view(),
        name="delete_cve_comment",
    ),
]
