# Generated by Django 4.2.3 on 2023-10-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0004_add_report_upsert_procedure'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='change',
            constraint=models.UniqueConstraint(fields=('created_at', 'cve_id', 'commit'), name='ix_unique_cve_commit_created_at'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('created_at', 'change_id', 'type'), name='ix_unique_change_type_created_at'),
        ),
    ]
